-- =============================================
-- Nursing Records - 17 Modules (18 Tables)
-- Database: nurse
-- =============================================

-- 1. การบันทึกการรับผู้ป่วย (Admit Record)
CREATE TABLE IF NOT EXISTS `nursing_admit_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) DEFAULT NULL,
  `record_datetime` DATETIME NOT NULL,
  `admit_from` ENUM('ER','OPD','OR','ICU','WARD','REFER') DEFAULT NULL,
  `admit_method` ENUM('walk','wheelchair','stretcher','ambulance') DEFAULT NULL,
  `admit_reason` VARCHAR(500) DEFAULT NULL,
  `chief_complaint` TEXT DEFAULT NULL,
  `present_illness` TEXT DEFAULT NULL,
  `past_illness` TEXT DEFAULT NULL,
  `allergies` VARCHAR(500) DEFAULT NULL,
  `current_medications` VARCHAR(500) DEFAULT NULL,
  `general_appearance` ENUM('good','fair','poor','critical') DEFAULT NULL,
  `skin_condition` ENUM('normal','dry','edema','wound','rash','jaundice') DEFAULT NULL,
  `mobility` ENUM('independent','assist','bedridden','wheelchair') DEFAULT NULL,
  `communication` ENUM('normal','difficulty','unable','interpreter') DEFAULT NULL,
  `religion` ENUM('buddhism','islam','christianity','other') DEFAULT NULL,
  `occupation` VARCHAR(100) DEFAULT NULL,
  `vital_t` DECIMAL(4,1) DEFAULT NULL,
  `vital_p` INT DEFAULT NULL,
  `vital_r` INT DEFAULT NULL,
  `vital_bp` VARCHAR(10) DEFAULT NULL,
  `vital_o2sat` INT DEFAULT NULL,
  `consciousness` ENUM('alert','drowsy','stupor','coma') DEFAULT NULL,
  `pain_score` TINYINT DEFAULT NULL,
  `nutrition_screening` ENUM('normal','risk','malnutrition') DEFAULT NULL,
  `weight` DECIMAL(5,1) DEFAULT NULL,
  `height` DECIMAL(5,1) DEFAULT NULL,
  `bmi` DECIMAL(4,1) DEFAULT NULL,
  `diagnosis_summary` TEXT DEFAULT NULL,
  `treatment_summary` TEXT DEFAULT NULL,
  `caregiver_name` VARCHAR(100) DEFAULT NULL,
  `caregiver_relation` VARCHAR(50) DEFAULT NULL,
  `caregiver_phone` VARCHAR(20) DEFAULT NULL,
  `nursing_diagnosis` TEXT DEFAULT NULL,
  `nursing_plan` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_admit_an` (`an`),
  INDEX `idx_admit_ward` (`ward_code`),
  INDEX `idx_admit_staff` (`staff_id`),
  INDEX `idx_admit_datetime` (`record_datetime`),
  INDEX `idx_admit_deleted` (`is_deleted`),
  INDEX `idx_admit_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_admit_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. แบบบันทึกสัญญาณชีพ (Vital Signs Record)
CREATE TABLE IF NOT EXISTS `nursing_vital_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `vital_t` DECIMAL(4,1) DEFAULT NULL,
  `vital_p` INT DEFAULT NULL,
  `vital_r` INT DEFAULT NULL,
  `vital_bp_s` INT DEFAULT NULL,
  `vital_bp_d` INT DEFAULT NULL,
  `vital_o2sat` INT DEFAULT NULL,
  `pain_score` TINYINT DEFAULT NULL,
  `consciousness` ENUM('Alert','Drowsy','Stupor','Coma') DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_vital_an` (`an`),
  INDEX `idx_vital_ward` (`ward_code`),
  INDEX `idx_vital_staff` (`staff_id`),
  INDEX `idx_vital_datetime` (`record_datetime`),
  INDEX `idx_vital_deleted` (`is_deleted`),
  INDEX `idx_vital_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_vital_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. บันทึกทางการพยาบาล (Nursing Progress Notes)
CREATE TABLE IF NOT EXISTS `nursing_progress_notes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `focus` VARCHAR(200) DEFAULT NULL,
  `note_type` VARCHAR(10) DEFAULT 'DAR',
  `subjective` TEXT DEFAULT NULL,
  `objective` TEXT DEFAULT NULL,
  `assessment` TEXT DEFAULT NULL,
  `intervention` TEXT DEFAULT NULL,
  `plan` TEXT DEFAULT NULL,
  `evaluation` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_nursing_an` (`an`),
  INDEX `idx_nursing_ward` (`ward_code`),
  INDEX `idx_nursing_staff` (`staff_id`),
  INDEX `idx_nursing_datetime` (`record_datetime`),
  INDEX `idx_nursing_deleted` (`is_deleted`),
  INDEX `idx_nursing_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_nursing_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. แผนการพยาบาล (Nursing Care Plan)
CREATE TABLE IF NOT EXISTS `nursing_care_plans` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `start_date` DATE NOT NULL,
  `priority` ENUM('high','medium','low') NOT NULL,
  `nursing_diagnosis` VARCHAR(500) NOT NULL,
  `related_to` TEXT DEFAULT NULL,
  `goal` TEXT DEFAULT NULL,
  `expected_outcome` TEXT DEFAULT NULL,
  `interventions` TEXT DEFAULT NULL,
  `evaluation` TEXT DEFAULT NULL,
  `evaluation_date` DATE DEFAULT NULL,
  `status` ENUM('active','resolved','revised') DEFAULT 'active',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_careplan_an` (`an`),
  INDEX `idx_careplan_ward` (`ward_code`),
  INDEX `idx_careplan_staff` (`staff_id`),
  INDEX `idx_careplan_start` (`start_date`),
  INDEX `idx_careplan_deleted` (`is_deleted`),
  INDEX `idx_careplan_an_start` (`an`, `start_date`),
  INDEX `idx_careplan_ward_start` (`ward_code`, `start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. บันทึกการได้รับและขับออกของสารน้ำ (I/O Record)
CREATE TABLE IF NOT EXISTS `nursing_io_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `io_type` ENUM('intake','output') NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `item_name` VARCHAR(200) DEFAULT NULL,
  `amount` DECIMAL(10,1) NOT NULL,
  `unit` ENUM('ml','L','unit','bag') DEFAULT 'ml',
  `route` ENUM('IV','Oral','NG','SC') DEFAULT NULL,
  `note` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_io_an` (`an`),
  INDEX `idx_io_ward` (`ward_code`),
  INDEX `idx_io_staff` (`staff_id`),
  INDEX `idx_io_datetime` (`record_datetime`),
  INDEX `idx_io_deleted` (`is_deleted`),
  INDEX `idx_io_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_io_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6a. คำสั่งยา (Medication Orders)
CREATE TABLE IF NOT EXISTS `nursing_medication_orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `order_datetime` DATETIME NOT NULL,
  `medication_name` VARCHAR(200) NOT NULL,
  `generic_name` VARCHAR(200) DEFAULT NULL,
  `dose` VARCHAR(50) NOT NULL,
  `unit` VARCHAR(20) DEFAULT NULL,
  `route` VARCHAR(20) NOT NULL,
  `frequency` VARCHAR(50) NOT NULL,
  `prn` TINYINT(1) DEFAULT 0,
  `prn_reason` VARCHAR(200) DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE DEFAULT NULL,
  `status` ENUM('active','discontinued','completed') DEFAULT 'active',
  `doctor_name` VARCHAR(100) DEFAULT NULL,
  `note` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_medorder_an` (`an`),
  INDEX `idx_medorder_ward` (`ward_code`),
  INDEX `idx_medorder_datetime` (`order_datetime`),
  INDEX `idx_medorder_deleted` (`is_deleted`),
  INDEX `idx_medorder_an_datetime` (`an`, `order_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6b. บันทึกการให้ยา (Medication Admins)
CREATE TABLE IF NOT EXISTS `nursing_medication_admins` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `admin_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') DEFAULT NULL,
  `medication_name` VARCHAR(200) NOT NULL,
  `dose_given` VARCHAR(50) NOT NULL,
  `route` VARCHAR(20) DEFAULT NULL,
  `site` VARCHAR(50) DEFAULT NULL,
  `status` ENUM('given','held','refused','omitted') NOT NULL,
  `held_reason` VARCHAR(500) DEFAULT NULL,
  `note` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_medadmin_order` (`order_id`),
  INDEX `idx_medadmin_an` (`an`),
  INDEX `idx_medadmin_ward` (`ward_code`),
  INDEX `idx_medadmin_staff` (`staff_id`),
  INDEX `idx_medadmin_datetime` (`admin_datetime`),
  INDEX `idx_medadmin_deleted` (`is_deleted`),
  INDEX `idx_medadmin_an_datetime` (`an`, `admin_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. บันทึกการดูแลพิเศษ (Special Care Records)
CREATE TABLE IF NOT EXISTS `nursing_special_care_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `care_type` VARCHAR(50) NOT NULL,
  `care_detail` VARCHAR(500) DEFAULT NULL,
  `procedure_done` TEXT DEFAULT NULL,
  `patient_response` TEXT DEFAULT NULL,
  `complications` VARCHAR(500) DEFAULT NULL,
  `equipment_used` VARCHAR(500) DEFAULT NULL,
  `next_plan` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_special_an` (`an`),
  INDEX `idx_special_ward` (`ward_code`),
  INDEX `idx_special_staff` (`staff_id`),
  INDEX `idx_special_datetime` (`record_datetime`),
  INDEX `idx_special_deleted` (`is_deleted`),
  INDEX `idx_special_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_special_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. บันทึกการศึกษาและให้ความรู้ (Patient Education)
CREATE TABLE IF NOT EXISTS `nursing_education_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `topic` VARCHAR(500) NOT NULL,
  `target_audience` VARCHAR(200) DEFAULT NULL,
  `teaching_method` VARCHAR(50) DEFAULT NULL,
  `content_taught` TEXT DEFAULT NULL,
  `materials_used` VARCHAR(500) DEFAULT NULL,
  `learner_response` TEXT DEFAULT NULL,
  `understanding_level` ENUM('excellent','good','fair','poor','unable') DEFAULT NULL,
  `barriers` VARCHAR(500) DEFAULT NULL,
  `follow_up_plan` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_education_an` (`an`),
  INDEX `idx_education_ward` (`ward_code`),
  INDEX `idx_education_staff` (`staff_id`),
  INDEX `idx_education_datetime` (`record_datetime`),
  INDEX `idx_education_deleted` (`is_deleted`),
  INDEX `idx_education_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_education_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. บันทึกการส่งเวร (Nursing Handover / SBAR)
CREATE TABLE IF NOT EXISTS `nursing_handover_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `handover_datetime` DATETIME NOT NULL,
  `shift_from` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `shift_to` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `nurse_from` VARCHAR(100) NOT NULL,
  `nurse_to` VARCHAR(100) NOT NULL,
  `situation` TEXT DEFAULT NULL,
  `background` TEXT DEFAULT NULL,
  `assessment` TEXT DEFAULT NULL,
  `recommendation` TEXT DEFAULT NULL,
  `pending_orders` TEXT DEFAULT NULL,
  `pending_labs` TEXT DEFAULT NULL,
  `iv_fluid_status` VARCHAR(500) DEFAULT NULL,
  `diet` VARCHAR(200) DEFAULT NULL,
  `activity` VARCHAR(200) DEFAULT NULL,
  `safety_concerns` VARCHAR(500) DEFAULT NULL,
  `family_issues` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_handover_an` (`an`),
  INDEX `idx_handover_ward` (`ward_code`),
  INDEX `idx_handover_staff` (`staff_id`),
  INDEX `idx_handover_datetime` (`handover_datetime`),
  INDEX `idx_handover_deleted` (`is_deleted`),
  INDEX `idx_handover_an_datetime` (`an`, `handover_datetime`),
  INDEX `idx_handover_ward_datetime` (`ward_code`, `handover_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. บันทึกการจำหน่าย (Discharge Record)
CREATE TABLE IF NOT EXISTS `nursing_discharge_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `discharge_datetime` DATETIME NOT NULL,
  `discharge_type` ENUM('physician_order','against_advice','transfer','death','escape') NOT NULL,
  `discharge_condition` ENUM('improved','recovered','unchanged','worse','death') NOT NULL,
  `vital_t` DECIMAL(4,1) DEFAULT NULL,
  `vital_p` INT DEFAULT NULL,
  `vital_r` INT DEFAULT NULL,
  `vital_bp` VARCHAR(10) DEFAULT NULL,
  `vital_o2sat` INT DEFAULT NULL,
  `diagnosis_summary` TEXT DEFAULT NULL,
  `treatment_summary` TEXT DEFAULT NULL,
  `procedure_done` TEXT DEFAULT NULL,
  `medication_instructions` TEXT DEFAULT NULL,
  `diet_instructions` TEXT DEFAULT NULL,
  `activity_instructions` TEXT DEFAULT NULL,
  `wound_care_instructions` TEXT DEFAULT NULL,
  `warning_signs` TEXT DEFAULT NULL,
  `follow_up_appointment` VARCHAR(500) DEFAULT NULL,
  `education_completed` TINYINT(1) DEFAULT 0,
  `medication_provided` TINYINT(1) DEFAULT 0,
  `documents_given` TINYINT(1) DEFAULT 0,
  `transportation_arranged` TINYINT(1) DEFAULT 0,
  `referral_arranged` TINYINT(1) DEFAULT 0,
  `discharged_with` ENUM('relative','self','ambulance','refer_team') DEFAULT NULL,
  `caregiver_name` VARCHAR(100) DEFAULT NULL,
  `caregiver_phone` VARCHAR(20) DEFAULT NULL,
  `discharge_destination` VARCHAR(200) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_discharge_an` (`an`),
  INDEX `idx_discharge_ward` (`ward_code`),
  INDEX `idx_discharge_staff` (`staff_id`),
  INDEX `idx_discharge_datetime` (`record_datetime`),
  INDEX `idx_discharge_deleted` (`is_deleted`),
  INDEX `idx_discharge_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_discharge_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. แบบประเมินความเสี่ยงพลัดตกหกล้ม (Fall Risk - Morse Fall Scale)
CREATE TABLE IF NOT EXISTS `nursing_fall_risk_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `history_of_falling` TINYINT NOT NULL,
  `secondary_diagnosis` TINYINT NOT NULL,
  `ambulatory_aid` TINYINT NOT NULL,
  `iv_heparin_lock` TINYINT NOT NULL,
  `gait` TINYINT NOT NULL,
  `mental_status` TINYINT NOT NULL,
  `total_score` INT NOT NULL,
  `risk_level` ENUM('low','moderate','high') NOT NULL,
  `interventions` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_fallrisk_an` (`an`),
  INDEX `idx_fallrisk_ward` (`ward_code`),
  INDEX `idx_fallrisk_staff` (`staff_id`),
  INDEX `idx_fallrisk_datetime` (`record_datetime`),
  INDEX `idx_fallrisk_deleted` (`is_deleted`),
  INDEX `idx_fallrisk_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_fallrisk_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. แบบประเมินแผลกดทับ (Braden Scale)
CREATE TABLE IF NOT EXISTS `nursing_braden_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `sensory_perception` TINYINT NOT NULL,
  `moisture` TINYINT NOT NULL,
  `activity` TINYINT NOT NULL,
  `mobility` TINYINT NOT NULL,
  `nutrition` TINYINT NOT NULL,
  `friction_shear` TINYINT NOT NULL,
  `total_score` INT NOT NULL,
  `risk_level` ENUM('very_high','high','moderate','mild','no_risk') NOT NULL,
  `interventions` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_braden_an` (`an`),
  INDEX `idx_braden_ward` (`ward_code`),
  INDEX `idx_braden_staff` (`staff_id`),
  INDEX `idx_braden_datetime` (`record_datetime`),
  INDEX `idx_braden_deleted` (`is_deleted`),
  INDEX `idx_braden_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_braden_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. แบบประเมินความปวด (Pain Assessment)
CREATE TABLE IF NOT EXISTS `nursing_pain_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `assessment_tool` ENUM('NRS','VAS','Wong-Baker','FLACC','BPS') NOT NULL,
  `pain_score` TINYINT NOT NULL,
  `pain_level` ENUM('no_pain','mild','moderate','severe','worst') NOT NULL,
  `location` VARCHAR(100) DEFAULT NULL,
  `character` VARCHAR(50) DEFAULT NULL,
  `onset` VARCHAR(200) DEFAULT NULL,
  `duration` VARCHAR(100) DEFAULT NULL,
  `aggravating` VARCHAR(500) DEFAULT NULL,
  `alleviating` VARCHAR(500) DEFAULT NULL,
  `intervention` TEXT DEFAULT NULL,
  `reassess_score` TINYINT DEFAULT NULL,
  `reassess_time` VARCHAR(50) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_pain_an` (`an`),
  INDEX `idx_pain_ward` (`ward_code`),
  INDEX `idx_pain_staff` (`staff_id`),
  INDEX `idx_pain_datetime` (`record_datetime`),
  INDEX `idx_pain_deleted` (`is_deleted`),
  INDEX `idx_pain_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_pain_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. บันทึกการทำแผล (Wound Care Record)
CREATE TABLE IF NOT EXISTS `nursing_wound_care_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `wound_type` VARCHAR(50) NOT NULL,
  `wound_location` VARCHAR(50) NOT NULL,
  `wound_size` VARCHAR(50) DEFAULT NULL,
  `wound_stage` ENUM('Stage I','Stage II','Stage III','Stage IV','Unstageable','DTI') DEFAULT NULL,
  `wound_appearance` VARCHAR(50) DEFAULT NULL,
  `exudate_type` ENUM('Serous','Sanguineous','Serosanguineous','Purulent') DEFAULT NULL,
  `exudate_amount` ENUM('ไม่มี','เล็กน้อย','ปานกลาง','มาก') DEFAULT NULL,
  `surrounding_skin` VARCHAR(200) DEFAULT NULL,
  `odor` ENUM('ไม่มี','เล็กน้อย','มาก') DEFAULT NULL,
  `pain_score` TINYINT DEFAULT NULL,
  `cleansing_solution` VARCHAR(50) DEFAULT NULL,
  `dressing_type` VARCHAR(50) DEFAULT NULL,
  `procedure_detail` TEXT DEFAULT NULL,
  `wound_status` ENUM('improving','stable','worsening','healed') NOT NULL,
  `next_dressing` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_wound_an` (`an`),
  INDEX `idx_wound_ward` (`ward_code`),
  INDEX `idx_wound_staff` (`staff_id`),
  INDEX `idx_wound_datetime` (`record_datetime`),
  INDEX `idx_wound_deleted` (`is_deleted`),
  INDEX `idx_wound_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_wound_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. บันทึกการผูกยึด (Restraint Record)
CREATE TABLE IF NOT EXISTS `nursing_restraint_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `restraint_type` VARCHAR(50) NOT NULL,
  `restraint_site` JSON NOT NULL,
  `indication` VARCHAR(100) NOT NULL,
  `physician_order` TINYINT(1) DEFAULT 0,
  `start_time` DATETIME NOT NULL,
  `release_time` DATETIME DEFAULT NULL,
  `duration` VARCHAR(50) DEFAULT NULL,
  `circulation_check` TINYINT(1) DEFAULT 0,
  `skin_check` TINYINT(1) DEFAULT 0,
  `rom_exercise` TINYINT(1) DEFAULT 0,
  `repositioning` TINYINT(1) DEFAULT 0,
  `nutrition_hydration` TINYINT(1) DEFAULT 0,
  `toileting` TINYINT(1) DEFAULT 0,
  `patient_response` TEXT DEFAULT NULL,
  `complications` TEXT DEFAULT NULL,
  `status` ENUM('active','released','discontinued') NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_restraint_an` (`an`),
  INDEX `idx_restraint_ward` (`ward_code`),
  INDEX `idx_restraint_staff` (`staff_id`),
  INDEX `idx_restraint_datetime` (`record_datetime`),
  INDEX `idx_restraint_deleted` (`is_deleted`),
  INDEX `idx_restraint_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_restraint_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 16. แบบประเมินระดับความรู้สึกตัว (Glasgow Coma Scale - GCS)
CREATE TABLE IF NOT EXISTS `nursing_gcs_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `eye_opening` TINYINT NOT NULL,
  `verbal_response` TINYINT NOT NULL,
  `motor_response` TINYINT NOT NULL,
  `total_score` INT NOT NULL,
  `level` ENUM('coma_deep','severe','moderate','mild') NOT NULL,
  `pupil_left` VARCHAR(20) DEFAULT NULL,
  `pupil_right` VARCHAR(20) DEFAULT NULL,
  `pupil_reaction_left` ENUM('brisk','sluggish','fixed') DEFAULT NULL,
  `pupil_reaction_right` ENUM('brisk','sluggish','fixed') DEFAULT NULL,
  `additional_notes` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_gcs_an` (`an`),
  INDEX `idx_gcs_ward` (`ward_code`),
  INDEX `idx_gcs_staff` (`staff_id`),
  INDEX `idx_gcs_datetime` (`record_datetime`),
  INDEX `idx_gcs_deleted` (`is_deleted`),
  INDEX `idx_gcs_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_gcs_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 17. แบบประเมินสุขภาพจิต/ความวิตกกังวล (Mental Health Assessment)
CREATE TABLE IF NOT EXISTS `nursing_mental_health_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(20) NOT NULL,
  `ward_code` VARCHAR(20) NOT NULL,
  `ward_name` VARCHAR(100) DEFAULT NULL,
  `staff_id` VARCHAR(20) NOT NULL,
  `nurse_name` VARCHAR(100) NOT NULL,
  `record_datetime` DATETIME NOT NULL,
  `shift` ENUM('ดึก','เช้า','บ่าย') NOT NULL,
  `assessment_tool` ENUM('ST-5','2Q','9Q') NOT NULL,
  `q1_score` TINYINT DEFAULT 0,
  `q2_score` TINYINT DEFAULT 0,
  `q3_score` TINYINT DEFAULT 0,
  `q4_score` TINYINT DEFAULT 0,
  `q5_score` TINYINT DEFAULT 0,
  `q6_score` TINYINT DEFAULT 0,
  `q7_score` TINYINT DEFAULT 0,
  `q8_score` TINYINT DEFAULT 0,
  `q9_score` TINYINT DEFAULT 0,
  `total_score` INT NOT NULL,
  `risk_level` VARCHAR(30) NOT NULL,
  `mood` VARCHAR(50) DEFAULT NULL,
  `sleep_pattern` VARCHAR(200) DEFAULT NULL,
  `appetite` VARCHAR(200) DEFAULT NULL,
  `social_interaction` VARCHAR(200) DEFAULT NULL,
  `interventions` TEXT DEFAULT NULL,
  `referral` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(20) DEFAULT NULL,
  `updated_by` VARCHAR(20) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_mental_an` (`an`),
  INDEX `idx_mental_ward` (`ward_code`),
  INDEX `idx_mental_staff` (`staff_id`),
  INDEX `idx_mental_datetime` (`record_datetime`),
  INDEX `idx_mental_deleted` (`is_deleted`),
  INDEX `idx_mental_an_datetime` (`an`, `record_datetime`),
  INDEX `idx_mental_ward_datetime` (`ward_code`, `record_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
